In [3]:
import numpy as np
import pandas as pd
from astropy.io import fits
from matplotlib import pyplot as plt

In [52]:
data = pd.read_csv('Data/ztf_crm/ztf_crm.csv', header=None)
data.head()

                                                   0
0  lightcurve_ztf_20221020148032_000686_zg_c01_x_...
1  lightcurve_ztf_20221020148032_000686_zg_c01_x_...
2  lightcurve_ztf_20221020148032_000686_zg_c01_x_...
3  lightcurve_ztf_20221020148032_000686_zg_c01_x_...
4  lightcurve_ztf_20221020148032_000686_zg_c01_x_...

In [53]:
data.drop(data.index[-1], inplace=True)
data.tail()

                                                       0
18997  lightcurve_ztf_20221020148032_000686_zg_c13_x_...
18998  lightcurve_ztf_20221020148032_000686_zg_c13_x_...
18999  lightcurve_ztf_20221020148032_000686_zg_c13_x_...
19000  lightcurve_ztf_20221020148032_000686_zg_c13_x_...
19001  lightcurve_ztf_20221020148032_000686_zg_c13_x_...

In [54]:
temp = np.array([np.array(name.split('_')[2:]) for name in data[0].values])

data['rundate'] = temp[:,0]
data['runnumber'] = temp[:,1]
data['filter'] = temp[:,2]
data['chip'] = temp[:,3]
data['segment'] = temp[:,-4]

data['source_xy'] = [t[:-4] for t in temp[:,-2] + temp[:,-1]]
data

,0,rundate,runnumber,filter,chip,segment,source_xy
0,lightcurve_ztf_20221020148032_000686_zg_c01_x_...,20221020148032,000686,zg,c01,0000,01270544
1,lightcurve_ztf_20221020148032_000686_zg_c01_x_...,20221020148032,000686,zg,c01,0000,01400236
2,lightcurve_ztf_20221020148032_000686_zg_c01_x_...,20221020148032,000686,zg,c01,0000,03062754
3,lightcurve_ztf_20221020148032_000686_zg_c01_x_...,20221020148032,000686,zg,c01,0000,03191422
4,lightcurve_ztf_20221020148032_000686_zg_c01_x_...,20221020148032,000686,zg,c01,0000,03632215
...,...,...,...,...,...,...,...
18997,lightcurve_ztf_20221020148032_000686_zg_c13_x_...,20221020148032,000686,zg,c13,0021,11080211
18998,lightcurve_ztf_20221020148032_000686_zg_c13_x_...,20221020148032,000686,zg,c13,0021,11981762
18999,lightcurve_ztf_20221020148032_000686_zg_c13_x_...,20221020148032,000686,zg,c13,0021,12111982
19000,lightcurve_ztf_20221020148032_000686_zg_c13_x_...,20221020148032,000686,zg,c13,0021,12450206
19001,lightcurve_ztf_20221020148032_000686_zg_c13_x_...,20221020148032,000686,zg,c13,0021,14430756

In [59]:
data.groupby(['rundate', 'runnumber', 'filter', 'chip', 'source_xy']).count()

                                                 0  segment
rundate        runnumber filter chip source_xy
20221020148032 000686    zg     c01  01270544   30       30
                                     01400236   30       30
                                     03062754   30       30
                                     03191422   30       30
                                     03632215   30       30
...                                             ..      ...
                                c13  28250454   21       21
                                     28661585   21       21
                                     28861749   21       21
                                     29011796   21       21
                                     30212495   21       21

[649 rows x 2 columns]

In [61]:
data[0][(data['chip'] == 'c05') & (data['segment'] == '0000')].values

array(['lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0064_0100.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0128_2400.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0385_1692.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0557_2309.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0595_2800.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0634_2900.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0803_1469.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1054_0757.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1102_2897.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1207_2559.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1237_0106.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1464_1201.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1831_0342.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1939_1246.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1955_2277.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1966_2273.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2058_2074.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2080_1989.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2120_1468.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2273_1615.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2468_1535.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2481_0690.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2497_1058.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2587_2848.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2701_0100.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2723_0435.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2793_2244.csv'],
      dtype=object)

In [63]:
arr = np.zeros(data[(data['chip'] == 'c05') & (data['segment'] == '0000')].values.shape[0])

for i, name in enumerate(data[0][(data['chip'] == 'c05') & (data['segment'] == '0000')].values):
    source = pd.read_csv(f'Data/ztf_crm/{name}')
    flux = source['flux_hap_2'].values
    middle_flux_mean = flux[int(len(flux) / 2 - 50) : int(len(flux) / 2 + 50)].mean()
    arr[i] = middle_flux_mean

In [64]:
source

,position_id,x_input,y_input,row_index,flux_hap_2,flux_hap_3,flux_hap_4,flux_hap_5,max_col
0,2,2793.0,2244.0,0,2516.133789,4253.924805,6048.779785,7888.686035,2793.0
1,2,2793.0,2244.0,1,2409.422852,4100.144043,5860.849609,7664.640137,2793.0
2,2,2793.0,2244.0,2,2442.931885,4122.286621,5867.832031,7660.407227,2793.0
3,2,2793.0,2244.0,3,2442.871094,4102.205078,5821.974609,7570.725586,2793.0
4,2,2793.0,2244.0,4,2420.821045,4099.837891,5840.750488,7611.558105,2793.0
...,...,...,...,...,...,...,...,...,...
3075,2,2793.0,2244.0,3075,2369.789307,3941.815186,5589.164062,7278.348633,2793.0
3076,2,2793.0,2244.0,3076,2433.523682,4072.189453,5793.222168,7554.734375,2793.0
3077,2,2793.0,2244.0,3077,2473.091309,4174.756836,5953.081543,7768.902344,2793.0
3078,2,2793.0,2244.0,3078,2458.365479,4113.749023,5847.515625,7621.072754,2793.0
3079,2,2793.0,2244.0,3079,2375.926270,3973.717285,5647.229980,7355.024902,2793.0

In [66]:
testnames = data[0][(data['chip'] == 'c05') & (data['segment'] == '0000')].values[np.argwhere(arr >= np.sort(arr)[-10]).flatten()] #get names of the 10 sources with highest mean flux

In [67]:
testnames

array(['lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0385_1692.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_0557_2309.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1237_0106.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1955_2277.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_1966_2273.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2080_1989.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2468_1535.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2481_0690.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2497_1058.csv',
       'lightcurve_ztf_20221020148032_000686_zg_c05_x_0000_1_2793_2244.csv'],
      dtype=object)

In [74]:
testlcs = []

for i, name in enumerate(testnames):
    source = pd.read_csv(f'Data/ztf_crm/{name}')
    testlcs.append(source['flux_hap_2'].values)


testlcs = np.array(testlcs)
testlcs

array([[ 479.50537109,  480.55554199,  467.22210693, ...,  475.29821777,
         468.3828125 ,  501.60742188],
       [1451.39782715, 1425.5456543 , 1443.60095215, ..., 1429.61584473,
        1389.23181152, 1410.29699707],
       [3305.02783203, 3266.13623047, 3314.77246094, ..., 3031.54003906,
        3062.37890625, 3086.37451172],
       ...,
       [ 478.24914551,  523.55541992,  517.43560791, ...,  181.16139221,
         159.98736572,  180.68566895],
       [ 321.41522217,  320.87719727,  315.90609741, ...,  392.62402344,
         398.71276855,  410.99346924],
       [2516.13378906, 2409.42285156, 2442.93188477, ..., 2473.09130859,
        2458.36547852, 2375.92626953]], shape=(10, 3080))

In [75]:
#Standardize flux values
for i in range(len(testlcs)):
    testlcs[i] = (testlcs[i] - np.nanmean(testlcs[i])) / np.nanstd(testlcs[i])

In [71]:
np.save('Data/ztf_crm/testlcs_c05.npy', testlcs)